# Generated by Django 5.2.4 on 2025-08-01 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_active_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                (
                    "permissions_level",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("roll_number", models.CharField(blank=True, max_length=20)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kindergarten", "Kindergarten"),
                            ("1st", "1st Grade"),
                            ("2nd", "2nd Grade"),
                            ("3rd", "3rd Grade"),
                            ("4th", "4th Grade"),
                            ("5th", "5th Grade"),
                            ("6th", "6th Grade"),
                            ("7th", "7th Grade"),
                            ("8th", "8th Grade"),
                            ("9th", "9th Grade"),
                            ("10th", "10th Grade"),
                            ("11th", "11th Grade"),
                            ("12th", "12th Grade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("parent_guardian_name", models.CharField(blank=True, max_length=100)),
                ("parent_guardian_phone", models.CharField(blank=True, max_length=15)),
                (
                    "parent_guardian_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                ("medical_conditions", models.TextField(blank=True)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="classroom.classroom",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("workplace", models.CharField(blank=True, max_length=200)),
                ("work_phone", models.CharField(blank=True, max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="users.studentprofile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("specialization", models.CharField(blank=True, max_length=200)),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
