# Generated by Django 5.2.4 on 2025-08-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subject", "0002_subject_subject_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                            ("project", "Project"),
                            ("participation", "Participation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_earned", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "points_possible",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("date_assigned", models.DateField()),
                ("date_due", models.DateField(blank=True, null=True)),
                ("date_graded", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_graded"],
            },
        ),
    ]
